# Generated by Django 4.0.6 on 2022-08-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_food_type_food_alter_food_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('breakfast', 'صبحانه'), ('drinks', 'نهار'), ('lunch', 'نهار'), ('dinner', 'شام')], default='lunch', max_length=20, verbose_name='نوع غذا'),
        ),
    ]
